Areas/Admin/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using kayip_project.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace kayip_project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Admin_Role)]
    public class DashBoardController : Controller
    {
        private readonly ILogger<DashBoardController> _logger;

        public DashBoardController(ILogger<DashBoardController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Areas/Admin/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using kayip_project.Models;
using kayip_project.Repository.IRepository;
using kayip_project.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.Extensions.Logging;

namespace kayip_project.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Admin_Role)]
    public class MessageController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public MessageController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        { 
            return View();
        }

        public IActionResult Edit(int?id)
        {
            if(id==null || id == 0) return NotFound();
            Message message = _unitOfWork.Message.Get(u=>u.Id == id);
            if(message  == null) return NotFound();
            return View(message);
        }

        [HttpPost]
        public IActionResult Edit(Message message)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.Message.Update(message);
                _unitOfWork.Save();
                return RedirectToAction("Index");

            }
            return View();
        }

        #region API CALLS

        [HttpGet]        
        public IActionResult GetAll()
        {
            List<Message> messageObj = _unitOfWork.Message.GetAll().ToList();
            return Json(new {data = messageObj });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var messageToBeDeleted = _unitOfWork.Message.Get(u=>u.Id == id);
            if(messageToBeDeleted == null)
            {
                return Json(new {success = false, message = "Error while deleting Message"});
            }

            _unitOfWork.Message.Remove(messageToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Deleted Successfully"});
        }
        
        #endregion

    }

}

Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using kayip_project.Data;
using kayip_project.Models;
using kayip_project.Repository.IRepository;
using kayip_project.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Authorization;
using kayip_project.Utility;

namespace kayip_project.Areas.Admin.Controllers.Admin
{
    [Area("Admin")]
    [Authorize(Roles = SD.Admin_Role)]
    public class PostController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        //access the root folder
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PostController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        } 

        public IActionResult Index()
        {
            List<Post> postObj = _unitOfWork.Post.GetAll(includeProperties: "ApplicationUser").ToList();
            return View(postObj);
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            PostVM postVM = new()
            {
                UserList = _unitOfWork.ApplicationUser.GetAll().Select(u=> new SelectListItem
                {
                    Text = u.FName,
                    Value = u.Id.ToString()
                }),
                Post = new Post()
            };
            //create
             if(id == null || id == 0) return View(postVM);
             else
             {
                //update
                postVM.Post = _unitOfWork.Post.Get(u => u.Id == id);
                return View(postVM);

             }
        }

        [HttpPost]
        public IActionResult Upsert(PostVM postVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string postPath = Path.Combine(wwwRootPath, "images", "post");

                    if (!string.IsNullOrEmpty(postVM.Post.Image))
                    {
                        string sanitizedImagePath = Regex.Replace(postVM.Post.Image, @"\.\.[\\/]", string.Empty);
                        string oldImagePath = Path.Combine(wwwRootPath, sanitizedImagePath);

                        if (Path.GetFullPath(oldImagePath).StartsWith(wwwRootPath, StringComparison.OrdinalIgnoreCase))
                        {
                            var fileInfo = new System.IO.FileInfo(oldImagePath);
                            if (fileInfo.Exists)
                            {
                                fileInfo.Delete();
                            }
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(postPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    postVM.Post.Image = Path.Combine("images", "post", fileName).Replace("\\", "/");
                }
                if (postVM.Post.Id == 0)
                {
                    _unitOfWork.Post.Add(postVM.Post);
                }
                else
                {
                    _unitOfWork.Post.Update(postVM.Post);
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(postVM);
        }
        
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Post> postObj = _unitOfWork.Post.GetAll(includeProperties: "ApplicationUser").ToList();
            return Json(new {data = postObj });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var postToBeDeleted = _unitOfWork.Post.Get(u=>u.Id == id);
            if(postToBeDeleted == null)
            {
                return Json(new {success = false, message = "Error while deleting post"});
            }

            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, postToBeDeleted.Image.TrimStart('\\'));

            if(System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Post.Remove(postToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Deleted Successfully"});
        }
        
        #endregion
    }
}

Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using kayip_project.Data;
using kayip_project.Models;
using kayip_project.Repository.IRepository;
using kayip_project.Utility;
using kayip_project.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace kayip_project.Areas.Admin.Controllers.Admin
{
    [Area("Admin")]
    [Authorize(Roles = SD.Admin_Role)]
    public class UserController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        public UserController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork)
        {
            _roleManager = roleManager;
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id);
            
            var userRole = (await _userManager.GetRolesAsync(user)).FirstOrDefault();

            UserVM userVM = new()
            {
                ApplicationUser = (ApplicationUser)user,
                RoleList = _roleManager.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id, // Assuming i.Id is already a string
                    Selected = i.Name == userRole // Set Selected based on user's current role name
                }),
            };

            return View(userVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserVM userVM)
        {
            string oldRole = (await _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == userVM.ApplicationUser.Id))).FirstOrDefault();

            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userVM.ApplicationUser.Id);
            if (applicationUser != null)
            {
                applicationUser.FName = userVM.ApplicationUser.FName;
                applicationUser.LName = userVM.ApplicationUser.LName;
                applicationUser.City = userVM.ApplicationUser.City;
                applicationUser.District = userVM.ApplicationUser.District;
                applicationUser.Email = userVM.ApplicationUser.Email;

                _unitOfWork.ApplicationUser.Update(applicationUser);
                _unitOfWork.Save();
            }

            // Ensure role ID is valid
            string roleId = userVM.ApplicationUser.Role; // Assuming userVM.ApplicationUser.Role is the role ID

            var role = await _roleManager.FindByIdAsync(roleId);

            if (role != null && role.Name != oldRole)
            {
                // Role exists and is different from the old role
                if (!string.IsNullOrEmpty(oldRole))
                {
                    await _userManager.RemoveFromRoleAsync(applicationUser, oldRole);
                }

                // Add the user to the new role by ID
                await _userManager.AddToRoleAsync(applicationUser, role.Name);

                _unitOfWork.ApplicationUser.Update(applicationUser);
                _unitOfWork.Save();
            }

            return RedirectToAction("Index");
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> userList = _unitOfWork.ApplicationUser.GetAll().ToList();

            foreach(var user in userList)
            {
                user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
            }

            return Json(new {data = userList});
        }

        [HttpDelete]
        public IActionResult Delete(string? id)
        {
            var userToBeDeleted = _userManager.FindByIdAsync(id).GetAwaiter().GetResult();
            if(userToBeDeleted == null)
            {
                return Json(new {success = false, message = "Error while deleting post"});
            }
            // Retrieve user roles and remove them
            var roles = _userManager.GetRolesAsync(userToBeDeleted).GetAwaiter().GetResult();
            if (roles.Any())
            {
                foreach (var role in roles)
                {
                    var result = _userManager.RemoveFromRoleAsync(userToBeDeleted, role).GetAwaiter().GetResult();
                    if (!result.Succeeded)
                    {
                        return Json(new { success = false, message = "Error while removing user roles" });
                    }
                }
            }
                // Delete the user
                var deleteResult = _userManager.DeleteAsync(userToBeDeleted).GetAwaiter().GetResult();
                if (!deleteResult.Succeeded)
                {
                    return Json(new { success = false, message = "Error while deleting user" });
                }
    return Json(new { success = true, message = "Deleted Successfully" });

        }

        [HttpPost]
        public IActionResult LockUnLock([FromBody]string id)
        {
            var objFromDb = _unitOfWork.ApplicationUser.Get(u=> u.Id == id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Error while locking/unlocking"});
            }

            if(objFromDb.LockoutEnd !=null && objFromDb.LockoutEnd > DateTime.Now)
            {
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(100);
            }
            _unitOfWork.ApplicationUser.Update(objFromDb);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Locked successfully"});
        }
        #endregion

    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
<script src="https://cdn.tiny.cloud/1/dg3vci698bnad7v8c6ko7qeqrvwdwv2a9wtbgsb6mhzcytwr/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>

        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Admin Panel - Gören Var Mı?</title>
        <link href="~/Admin/css/styles.css" rel="stylesheet" />
        <link rel="stylesheet" href="//cdn.datatables.net/2.0.5/css/dataTables.dataTables.min.css">
        
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" asp-controller="DashBoard" asp-action="Index">Admin Panel</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

    <li class="nav-item">
        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button id="logout" type="submit" class="nav-link btn btn-link text-dark border-0">Logout</button> 
        </form>
    </li>

                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" asp-controller="DashBoard" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                                Users
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="User" asp-action="Index">Manage User</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePosts" aria-expanded="false" aria-controls="collapsePosts">
                                <div class="sb-nav-link-icon"><i class="fas fa-clipboard"></i></div>
                                Posts
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePosts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="Post" asp-action="Upsert">Create Post</a>
                                    <a class="nav-link" asp-controller="Post" asp-action="Index">Manage Post</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-comment"></i></div>
                                Messages
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="Message" asp-action="Index">Manage Message</a>
                                </nav>
                            </div>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @RenderBody()

                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2023</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/Admin/js/scripts.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="~/Admin/assets/demo/chart-bar-demo.js"></script>
                <script src="~/Admin/assets/demo/chart-area-demo.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
        <script src="//cdn.datatables.net/2.0.5/js/dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    </body>
</html>

Views/Shared/_Layout.cshtml
@using kayip_project.Utility
@using Microsoft.AspNetCore.Identity
@using kayip_project.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gören Var Mı?</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- Vendor CSS Files -->
    <link
      href="~/assets/vendor/bootstrap/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css"
      rel="stylesheet"
    />
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>


    <!-- Template Main CSS File -->
        <link href="~/assets/css/style.css" rel="stylesheet" />
</head>
<body>
    <header>
    <div class="collapse navbar-collapse custom-navmenu" id="main-navbar">
      <div class="container py-2 py-md-5">
        <div class="row">
            <div class="col-md-2 nav-item">
                <h3>
                                <a asp-controller="Home" asp-area="Customer" asp-action="WhatToDo">
              Ne yapmam gerekiyor?
          </a>
                </h3>
              </div>
          <div class="col-md-2 nav-item">
            <h3>
              <a asp-controller="Home" asp-area="Customer" asp-action="Help">
                Yardım edebilir miyim?
              </a>
              </h3>
          </div>
          <div class="col-md-2 nav-item">
            <h3><a asp-controller="Home" asp-area="Customer" asp-action="Index">
                    Ana sayfa
                  </a>
          </h3>
          </div>
             @if(User.IsInRole(SD.Admin_Role))
            {
            <div class="col-md-2 nav-item">
            <h3><a  asp-area="Admin" asp-controller="DashBoard" asp-action="Index">
              Admin Panel
          </a></h3>
          </div>
           }
           @if(User.IsInRole(SD.Admin_Role) || User.IsInRole(SD.User_Role))
           {
            <div class="col-md-2 nav-item">
            <h3><a asp-area="Customer" asp-controller="Post" asp-action="Index" >
             Gönderilerim
          </a></h3>
          </div> 
           }
          <div class="col-md-2 nav-item">
            <h3>
            <a asp-controller="Home" asp-area="Customer" asp-action="ContactUs">iletişim</a>
            </h3>
          </div>
          
              <partial name="_LoginPartial"/>
        </div>
      </div>
    </div>

    <nav class="navbar navbar-light custom-navbar"> 
      <div class="container">
        <a
          href="#"
          class="burger"
          data-bs-toggle="collapse"
          data-bs-target="#main-navbar"
        >
          <span></span>
        </a>
      </div>
    </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  <footer class="footer" role="contentinfo">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <p class="mb-1">
            &copy; Copyright Tüm Hakları Saklıdır.
          </p>
        </div>
        <div class="col-sm-6 social text-md-end">
          <a asp-area="Customer" asp-action="ContactUs"><span class="bi bi-envelope"></span></a>
        </div>
      </div>
    </div>
  </footer>
  <a href="" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
            @await RenderSectionAsync("Scripts", required: false)
    <!-- Vendor JS Files -->
        <script src="~/assets/js/main.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Template Main JS File -->
            </body>
</html>